---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: get
    image: golang:1.14.7
    commands:
      - go mod download

  - name: golangci-lint
    image: golangci/golangci-lint:v1.26.0
    commands:
      - golangci-lint run

  - name: test
    image: golang:1.14.7
    commands:
      - go test ./...

  - name: markdown
    image: 06kellyjac/markdownlint-cli
    commands:
      - markdownlint .

  - name: linelint
    image: fernandrone/linelint:latest
    pull: true

  - name: build
    image: golang:1.14.7
    commands:
      - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags "-w -s"
    environment:
      GOOS: linux
      GOARCH: amd64
    when:
      event: push
      branch: main

  - name: dockerhub 
    image: plugins/docker
    settings:
      repo: fernandrone/grace
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: tag

  - name: release
    image: golang:1.14.7
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - curl -sSL https://git.io/goreleaser | bash
    when:
      event: tag

trigger:
  event:
    - push
    - tag

image_pull_secrets:
  - dockerconfigjson
