---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: golangci-lint
    image: golangci/golangci-lint:v1.27.0
    commands:
      - golangci-lint run

  - name: test
    image: golang:1.17
    commands:
      - go test ./...

  - name: markdown
    image: 06kellyjac/markdownlint-cli
    commands:
      - markdownlint .

  - name: linelint
    image: fernandrone/linelint:latest
    pull: true

  - name: build
    image: golang:1.17
    commands:
      - make build
    depends_on:
      - golangci-lint
      - test
      - markdown
      - linelint
    when:
      event: push

  - name: dockerhub
    image: plugins/docker
    settings:
      repo: fernandrone/grace
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    depends_on:
      - golangci-lint
      - test
      - markdown
      - linelint
    when:
      event: tag

  - name: release
    image: golang:1.17
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - curl -sSL https://git.io/goreleaser | bash
    when:
      event: tag

trigger:
  event:
    - push
    - tag

image_pull_secrets:
  - dockerconfigjson
